In [1]:
from dqn_utils.models import *
from dqn_utils.utils import define_env, train, optimize_model
from adabyron_environment.AdaByronDEMO import AdaByronDEMO
from dqn_utils.memory import Memory
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import random
from collections import deque

In [2]:
env, policy_network, target_network, action_space  = define_env("test", ["aire1", "aire2"], baterias=["bateria1"], INPUT_SIZE=4)

#keras.utils.plot_model(policy_network, to_file='policy_network.png', show_shapes=True, show_layer_names=True, rankdir='TB', expand_nested=False, dpi=96)

Loading models...
Models not found, creating new ones...


In [3]:
tf.multiply(tf.expand_dims(tf.convert_to_tensor([1,2,3,4]),0), tf.expand_dims(tf.convert_to_tensor([1,2,3,4]),0))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 1,  4,  9, 16]])>

In [4]:
#Constant vars
K = 4
EPS_DECAY = 0.0000009
EPS_MIN = 0.1
#BATCH_SIZE = 32
BATCH_SIZE = 1
MAX_STEPS = 10000
STEP_UPDATE_MODEL = 5000


#model_type = "Dense" # Network (Dense)
curve_pred = [35.0, 42.5]
#curve_pred = [35.0, 42.5, 47.5,  38.5, 33.0, 41.0, 46.0, 37.0]
# curve_pred = [[random.randint(30, 50) for i in range(1440)]]

optimizer = tf.keras.optimizers.Adam(learning_rate=0.00025, clipnorm=1.0)
loss_function = tf.keras.losses.Huber()
seed = 42
gamma = 0.99
epsilon = 1
memory = Memory(10000) # Memory size


train(epsilon, MAX_STEPS, action_space, policy_network, EPS_DECAY, EPS_MIN, env, memory, BATCH_SIZE, STEP_UPDATE_MODEL, target_network, K, gamma, loss_function, optimizer, curve_pred)



1
[[ 0.   1.  35.  42.5]]
Mask
[<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 1.]], dtype=float32)>, <tf.Tensor: shape=(1, 7), dtype=float32, numpy=array([[0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>]
Qvalues
[<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-3.7256165 , -1.1320715 ,  0.51938045, -0.8152708 ]],
      dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[-1.4220036, -2.391089 ,  1.8369689,  2.1595116]], dtype=float32)>, <tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[ 2.185348  ,  1.2457836 ,  0.86008495, -0.9284277 , -1.480212  ,
        -1.287324  ,  0.20712316]], dtype=float32)>]
<class 'list'>
<class 'list'>


InvalidArgumentError: {{function_node __wrapped__Pack_N_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shapes of all inputs must match: values[0].shape = [1,4] != values[2].shape = [1,7] [Op:Pack] name: packed

In [ ]:
# import matplotlib.pyplot as plt
# curve_pred = [random.randint(30, 50) for i in range(1440)]
# curve_pred2 = [random.randint(0, 112) for i in range(1440)]
# curve_pred3 = [i for i in range(1440)]


# plt.figure(figsize=(90,6))
# plt.plot(curve_pred)
# plt.plot(curve_pred2)
# plt.savefig("salidaprimerentreno.png")
